export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY = "GET_COUNTRY";
export const ADD_COUNTRY = "ADD_COUNTRY"
export const CLEAN_SEARCH = "CLEAN_SEARCH"
export const DELETE_COUNTRY = "DELETE_COUNTRY"
export const ALL_COUNTRIES_TO_FILTER = "ALL_COUNTRIES_TO_FILTER"
export const ORDER_CARDS_ONE = "ORDER_CARDS_ONE"
export const ORDER_CARDS_TWO = "ORDER_CARDS_TWO"
export const FILTER_CARDS = "FILTER_CARDS"
export const CLONE_TO_FILTER = "CLONE_TO_FILTER"

export const ASCENDING = "ASCENDING"
export const DESCENDING = "DESCENDING"
export const BY_COUNTRY = "BY_COUNTRY"
export const BY_POPULATION = "BY_POPULATION"
export const BY_CONTINENT = "BY_CONTINENT"
export const BY_TOURIST_ACTIVITY = "BY_TOURIST_ACTIVITY"
